"""Integration tests for Block 15F-B — Configurable Algebraic Residual Selection.

Proves that the CONFIGURABLE_ALGEBRAIC residual-selection mode integrates
correctly with the 15F-A algebraic residual foundation and the 15E-B
residual-selection layer.

Acceptance stories
------------------
A1  Build a configurable single-loop scenario, declare algebraic residuals,
    request CONFIGURABLE_ALGEBRAIC — evaluate at zero-residual point.
A2  Perturb one unknown — residual becomes nonzero.
A3  Change component roles while keeping structure and explicit residual
    declarations — selection/evaluation behavior does not change.
A4  Missing scenario unknown produces incompatible selection and no evaluation.
A5  DECLARATION_ONLY mode continues to work alongside the new mode.
A6  CLOSURE_ONLY mode continues to work alongside the new mode.
A7  Reports from all three stack layers are JSON-serializable together.
A8  Evaluate using evaluate_selected_configurable_residuals (requires params).
A9  Pure selection with evaluate=False does not perform evaluation.
A10 Extra unknown values are silently ignored (15F-A documented behavior).
A11 Report includes residuals_inferred_from_roles=False and
    residuals_inferred_from_topology=False.

Validation stories
------------------
V1  CONFIGURABLE_ALGEBRAIC rejects missing algebraic_residual_set.
V2  CONFIGURABLE_ALGEBRAIC accepts a valid explicit algebraic residual set.
V3  CONFIGURABLE_ALGEBRAIC rejects incompatible set with missing scenario unknowns.
V4  Evaluation requires evaluate=True.
V5  Evaluation requires algebraic_unknown_values.
V6  result.no_solve is always True.
V7  Report is JSON-serializable.
V8  Report includes required unknown names and no-inference flags.

Regression stories
------------------
R1  Production contracts still show NO_CONTRIBUTE_METHOD for all 6 classes.
R2  inspect_known_production_component_contracts returns exactly 6 results.

Boundary stories (module-attribute checks)
------------------------------------------
B1  configurable_residual_selection imports no CoolProp or PropertyBackend.
B2  No contribute attribute in the selection module.
B3  No SystemState or FluidState in the selection module.
B4  No solve(network) or NetworkGraph.solve() in the selection module.

These tests do NOT:
  - Call any solver or root-finder.
  - Execute production component physics.
  - Call CoolProp, PropertyBackend, or correlations.
  - Assemble SystemState or construct FluidState.
  - Write files, use pandas, or use numpy.
  - Infer residuals from roles or topology.
"""

from __future__ import annotations

import inspect
import json

import pytest

from mpl_sim.network.closure_integration import build_combined_closure_residuals
from mpl_sim.network.configurable_algebraic_residuals import (
    ConfigurableAlgebraicResidualEvaluationResult,
    ConfigurableAlgebraicResidualSet,
    ImposedMassFlowResidualDeclaration,
    ImposedPressureResidualDeclaration,
    MassBalanceResidualDeclaration,
    PressureDifferenceResidualDeclaration,
    build_configurable_algebraic_residual_report,
    build_configurable_algebraic_residual_set,
    validate_algebraic_residuals_against_scenario,
)
from mpl_sim.network.configurable_residual_selection import (
    ConfigurableResidualMode,
    ConfigurableResidualSelectionRequest,
    build_configurable_residual_selection_report,
    evaluate_selected_configurable_residuals,
    select_configurable_residual_strategy,
)
from mpl_sim.network.configurable_scenarios import (
    ConfigurableScenarioBuildResult,
    ConfigurableScenarioSpec,
    ScenarioComponentRole,
    ScenarioComponentSpec,
    ScenarioConnectionSpec,
    ScenarioNodeSpec,
    build_configurable_scenario,
    build_configurable_scenario_report,
)
from mpl_sim.network.hydraulic_closures import (
    ImposedMassFlowClosure,
    ImposedPressureClosure,
    build_hydraulic_closure_residuals,
)
from mpl_sim.network.production_component_inspection import (
    ProductionComponentContractStatus,
    inspect_known_production_component_contracts,
)

# ---------------------------------------------------------------------------
# Scenario helper — simple 3-component single-branch loop
# ---------------------------------------------------------------------------
#
# Components: pump, evaporator, condenser
# Nodes: n_pump_out, n_evap_out, n_cond_out
# Connections: pump→n_pump_out, evaporator→n_evap_out, condenser→n_cond_out
#
# Unknowns generated by build_configurable_scenario:
#   mdot:pump, mdot:evaporator, mdot:condenser
#   P:n_pump_out, P:n_evap_out, P:n_cond_out
#
# We use a simple 3-component loop so we can control all unknowns.


def _make_spec(
    pump_role: ScenarioComponentRole = ScenarioComponentRole.PUMP,
    evap_role: ScenarioComponentRole = ScenarioComponentRole.EVAPORATOR,
    cond_role: ScenarioComponentRole = ScenarioComponentRole.CONDENSER,
) -> ConfigurableScenarioSpec:
    return ConfigurableScenarioSpec(
        scenario_id="test_simple_loop",
        components=(
            ScenarioComponentSpec("pump", pump_role),
            ScenarioComponentSpec("evaporator", evap_role),
            ScenarioComponentSpec("condenser", cond_role),
        ),
        nodes=(
            ScenarioNodeSpec("n_pump_out"),
            ScenarioNodeSpec("n_evap_out"),
            ScenarioNodeSpec("n_cond_out"),
        ),
        connections=(
            ScenarioConnectionSpec("pump", "n_cond_out", "n_pump_out"),
            ScenarioConnectionSpec("evaporator", "n_pump_out", "n_evap_out"),
            ScenarioConnectionSpec("condenser", "n_evap_out", "n_cond_out"),
        ),
    )


def _build_scenario(
    pump_role: ScenarioComponentRole = ScenarioComponentRole.PUMP,
    evap_role: ScenarioComponentRole = ScenarioComponentRole.EVAPORATOR,
    cond_role: ScenarioComponentRole = ScenarioComponentRole.CONDENSER,
) -> ConfigurableScenarioBuildResult:
    return build_configurable_scenario(_make_spec(pump_role, evap_role, cond_role))


# ---------------------------------------------------------------------------
# Algebraic residual declarations for the simple 3-component loop
#
# Unknowns: mdot:pump, mdot:evaporator, mdot:condenser
#           P:n_pump_out, P:n_evap_out, P:n_cond_out
#
# Residuals:
#   mass_balance (one per node, single-branch so trivial):
#     r_mb_pump_out  = mdot:pump - mdot:evaporator      [mass balance at n_pump_out]
#     r_mb_evap_out  = mdot:evaporator - mdot:condenser [mass balance at n_evap_out]
#   pressure residuals:
#     r_P_pump_out   = P:n_pump_out - P_pump_imposed
#     r_dp_evap      = P:n_evap_out - P:n_pump_out + evap_drop
#     r_dp_cond      = P:n_cond_out - P:n_evap_out + cond_drop
#   imposed mass flow:
#     r_mdot_pump    = mdot:pump - mdot_imposed
#
# Consistent point:
#   mdot_imposed      = 1.0 kg/s
#   P_pump_imposed    = 200_000 Pa
#   evap_drop         = 50_000 Pa  → P:n_evap_out = 150_000 Pa
#   cond_drop         = 30_000 Pa  → P:n_cond_out = 120_000 Pa
#
# At the consistent point all residuals = 0.0
# ---------------------------------------------------------------------------

_MDOT_IMPOSED = 1.0
_P_PUMP_IMPOSED = 200_000.0
_EVAP_DROP = 50_000.0
_COND_DROP = 30_000.0

_ZERO_UV: dict[str, float] = {
    "mdot:pump": _MDOT_IMPOSED,
    "mdot:evaporator": _MDOT_IMPOSED,
    "mdot:condenser": _MDOT_IMPOSED,
    "P:n_pump_out": _P_PUMP_IMPOSED,
    "P:n_evap_out": _P_PUMP_IMPOSED - _EVAP_DROP,  # 150_000
    "P:n_cond_out": _P_PUMP_IMPOSED - _EVAP_DROP - _COND_DROP,  # 120_000
}

_PERTURBED_UV: dict[str, float] = {
    **_ZERO_UV,
    "P:n_evap_out": 999_999.0,  # deliberately wrong
}


def _make_residual_set() -> ConfigurableAlgebraicResidualSet:
    return build_configurable_algebraic_residual_set(
        [
            MassBalanceResidualDeclaration(
                residual_name="r_mb_pump_out",
                incoming_unknown_names=("mdot:pump",),
                outgoing_unknown_names=("mdot:evaporator",),
            ),
            MassBalanceResidualDeclaration(
                residual_name="r_mb_evap_out",
                incoming_unknown_names=("mdot:evaporator",),
                outgoing_unknown_names=("mdot:condenser",),
            ),
            ImposedPressureResidualDeclaration(
                residual_name="r_P_pump_out",
                pressure_unknown="P:n_pump_out",
                imposed_value=_P_PUMP_IMPOSED,
            ),
            PressureDifferenceResidualDeclaration(
                residual_name="r_dp_evap",
                inlet_pressure_unknown="P:n_pump_out",
                outlet_pressure_unknown="P:n_evap_out",
                delta_p=_EVAP_DROP,
            ),
            PressureDifferenceResidualDeclaration(
                residual_name="r_dp_cond",
                inlet_pressure_unknown="P:n_evap_out",
                outlet_pressure_unknown="P:n_cond_out",
                delta_p=_COND_DROP,
            ),
            ImposedMassFlowResidualDeclaration(
                residual_name="r_mdot_pump",
                mass_flow_unknown="mdot:pump",
                imposed_value=_MDOT_IMPOSED,
            ),
        ]
    )


# ---------------------------------------------------------------------------
# A1: Zero-residual evaluation
# ---------------------------------------------------------------------------


class TestA1ZeroResidualEvaluation:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_mode_is_enum_member(self) -> None:
        assert ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC in ConfigurableResidualMode

    def test_selection_is_compatible(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is True
        assert result.selected_mode is ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC

    def test_evaluation_at_zero_residual_point(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is True
        assert result.evaluation_deferred is False
        assert result.evaluation_result is not None
        assert isinstance(result.evaluation_result, ConfigurableAlgebraicResidualEvaluationResult)
        for name, val in result.evaluation_result.residual_values.items():
            assert abs(val) < 1e-9, f"residual {name!r} should be zero; got {val}"
        assert result.evaluation_result.max_abs_residual < 1e-9
        assert result.evaluation_result.l2_norm < 1e-9

    def test_no_solve_always_true(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.no_solve is True
        assert result.evaluation_result.no_solve is True


# ---------------------------------------------------------------------------
# A2: Perturbed unknown gives nonzero residual
# ---------------------------------------------------------------------------


class TestA2PerturbedNonzeroResidual:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_perturbed_gives_nonzero(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_PERTURBED_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is True
        assert result.evaluation_result is not None
        # r_dp_evap should be nonzero since P:n_evap_out was perturbed
        rv = result.evaluation_result.residual_values
        assert abs(rv["r_dp_evap"]) > 1.0
        assert result.evaluation_result.max_abs_residual > 1.0


# ---------------------------------------------------------------------------
# A3: Role changes do not affect compatibility or evaluation
# ---------------------------------------------------------------------------


class TestA3RoleChangesDoNotAffectBehavior:
    def setup_method(self) -> None:
        self.residual_set = _make_residual_set()

    def _check_eval(self, build_result: ConfigurableScenarioBuildResult) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is True
        assert result.evaluation_performed is True
        for val in result.evaluation_result.residual_values.values():
            assert abs(val) < 1e-9

    def test_default_roles_evaluate_correctly(self) -> None:
        br = _build_scenario()
        self._check_eval(br)

    def test_all_generic_roles_evaluate_identically(self) -> None:
        br = _build_scenario(
            pump_role=ScenarioComponentRole.GENERIC,
            evap_role=ScenarioComponentRole.GENERIC,
            cond_role=ScenarioComponentRole.GENERIC,
        )
        self._check_eval(br)

    def test_mixed_roles_evaluate_identically(self) -> None:
        br = _build_scenario(
            pump_role=ScenarioComponentRole.ACCUMULATOR,
            evap_role=ScenarioComponentRole.PUMP,
            cond_role=ScenarioComponentRole.GENERIC,
        )
        self._check_eval(br)

    def test_roles_do_not_change_unknown_names(self) -> None:
        br_default = _build_scenario()
        br_generic = _build_scenario(
            pump_role=ScenarioComponentRole.GENERIC,
            evap_role=ScenarioComponentRole.GENERIC,
            cond_role=ScenarioComponentRole.GENERIC,
        )
        assert set(br_default.unknown_names) == set(br_generic.unknown_names)


# ---------------------------------------------------------------------------
# A4: Missing scenario unknown produces incompatible selection
# ---------------------------------------------------------------------------


class TestA4MissingScenarioUnknown:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()

    def test_residual_with_unknown_not_in_scenario(self) -> None:
        bad_set = build_configurable_algebraic_residual_set(
            [
                ImposedPressureResidualDeclaration(
                    residual_name="r_bad",
                    pressure_unknown="P:n_nonexistent_node",  # not in scenario
                    imposed_value=100_000.0,
                ),
            ]
        )
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=bad_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is False
        assert result.evaluation_performed is False
        assert result.evaluation_deferred is True
        reasons = " ".join(result.compatibility.reasons)
        assert "P:n_nonexistent_node" in reasons

    def test_evaluate_required_raises_on_incompatible(self) -> None:
        bad_set = build_configurable_algebraic_residual_set(
            [
                ImposedPressureResidualDeclaration(
                    residual_name="r_bad",
                    pressure_unknown="P:n_nonexistent_node",
                    imposed_value=100_000.0,
                ),
            ]
        )
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=bad_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        with pytest.raises(ValueError, match="not compatible"):
            evaluate_selected_configurable_residuals(req)


# ---------------------------------------------------------------------------
# A5/A6: Existing modes continue to work
# ---------------------------------------------------------------------------


class TestA5A6ExistingModesContinueToWork:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()

    def test_declaration_only_still_works(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.DECLARATION_ONLY,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is True
        assert result.evaluation_performed is False
        assert result.no_solve is True

    def test_closure_only_still_works(self) -> None:
        h_set = build_hydraulic_closure_residuals(
            [
                ImposedMassFlowClosure(
                    unknown_name="mdot:pump",
                    imposed_value=1.0,
                    residual_name="r_mdot_pump",
                ),
                ImposedPressureClosure(
                    unknown_name="P:n_pump_out",
                    imposed_value=200_000.0,
                    residual_name="r_P_pump_out",
                ),
            ]
        )
        c_set = build_combined_closure_residuals(hydraulic=h_set, thermal=None)
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CLOSURE_ONLY,
            closure_residual_set=c_set,
            closure_unknown_values={"mdot:pump": 1.0, "P:n_pump_out": 200_000.0},
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is True
        assert result.evaluation_performed is True
        assert result.no_solve is True


# ---------------------------------------------------------------------------
# A7: Reports are JSON-serializable together
# ---------------------------------------------------------------------------


class TestA7ReportsAreJSONSerializable:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_three_layer_reports_serialize_together(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        sel_result = select_configurable_residual_strategy(req)

        scenario_report = build_configurable_scenario_report(self.build_result)
        selection_report = build_configurable_residual_selection_report(sel_result)
        alg_report = build_configurable_algebraic_residual_report(sel_result.evaluation_result)

        combined = {
            "scenario": scenario_report,
            "selection": selection_report,
            "algebraic": alg_report,
        }
        serialized = json.dumps(combined)
        loaded = json.loads(serialized)

        assert loaded["selection"]["no_solve"] is True
        assert loaded["selection"]["selected_mode"] == "configurable_algebraic"
        assert loaded["algebraic"]["no_solve"] is True


# ---------------------------------------------------------------------------
# A8: evaluate_selected_configurable_residuals requires params
# ---------------------------------------------------------------------------


class TestA8EvaluateSelectedRequiresParams:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_evaluate_selected_succeeds_with_full_params(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = evaluate_selected_configurable_residuals(req)
        assert result.evaluation_performed is True
        assert result.evaluation_result is not None

    def test_evaluate_selected_raises_if_no_unknown_values(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            evaluate=True,
        )
        with pytest.raises(ValueError, match="algebraic_unknown_values"):
            evaluate_selected_configurable_residuals(req)

    def test_evaluate_selected_raises_if_no_residual_set(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            evaluate=True,
        )
        with pytest.raises(ValueError):
            evaluate_selected_configurable_residuals(req)


# ---------------------------------------------------------------------------
# A9: Pure selection (evaluate=False) does not perform evaluation
# ---------------------------------------------------------------------------


class TestA9PureSelectionNoEvaluation:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_evaluate_false_defers_evaluation(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=False,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is True
        assert result.evaluation_performed is False
        assert result.evaluation_deferred is True
        assert "evaluate" in result.evaluation_deferred_reason.lower()
        assert result.evaluation_result is None

    def test_evaluate_false_no_values_still_no_evaluation(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            evaluate=False,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is False
        assert result.evaluation_result is None


# ---------------------------------------------------------------------------
# A10: Extra unknown values silently ignored
# ---------------------------------------------------------------------------


class TestA10ExtraUnknownValuesSilentlyIgnored:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_extra_unknowns_do_not_raise(self) -> None:
        uv_with_extras = {
            **_ZERO_UV,
            "completely_irrelevant_unknown_xyz": 9999.0,
            "another_irrelevant": -42.0,
        }
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=uv_with_extras,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is True
        for val in result.evaluation_result.residual_values.values():
            assert abs(val) < 1e-9


# ---------------------------------------------------------------------------
# A11: Report includes no-inference flags
# ---------------------------------------------------------------------------


class TestA11ReportNoInferenceFlags:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_report_has_no_inference_flags(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        assert report["no_solve"] is True
        assert report["roles_selected_physics"] is False
        assert report["closures_inferred_from_roles"] is False
        assert report["residuals_inferred_from_roles"] is False
        assert report["residuals_inferred_from_topology"] is False

    def test_report_includes_required_unknown_names_in_reasons(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
        )
        result = select_configurable_residual_strategy(req)
        # Reasons should include required unknown names information
        reasons_text = " ".join(result.compatibility.reasons)
        assert "required unknown names" in reasons_text

    def test_evaluation_report_has_backend_configurable_algebraic(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        assert report["evaluation"]["backend"] == "configurable_algebraic"
        assert "residual_values" in report["evaluation"]
        assert "unknown_names_used" in report["evaluation"]


# ---------------------------------------------------------------------------
# V1: CONFIGURABLE_ALGEBRAIC rejects missing algebraic_residual_set
# ---------------------------------------------------------------------------


class TestV1MissingResidualSet:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()

    def test_no_algebraic_set_is_incompatible(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is False
        reasons = " ".join(result.compatibility.reasons)
        assert "None" in reasons or "algebraic_residual_set" in reasons

    def test_no_algebraic_set_defers_evaluation(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is False
        assert result.evaluation_deferred is True


# ---------------------------------------------------------------------------
# V2: CONFIGURABLE_ALGEBRAIC accepts a valid explicit set
# ---------------------------------------------------------------------------


class TestV2ValidSetIsAccepted:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_valid_set_is_compatible(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is True

    def test_valid_set_evaluates_without_error(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is True
        assert result.evaluation_result is not None


# ---------------------------------------------------------------------------
# V3: Incompatible set (missing scenario unknowns) rejects
# ---------------------------------------------------------------------------


class TestV3IncompatibleSetRejects:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()

    def test_all_unknowns_missing_is_incompatible(self) -> None:
        bad_set = build_configurable_algebraic_residual_set(
            [
                ImposedPressureResidualDeclaration(
                    residual_name="r_ghost1",
                    pressure_unknown="P:n_ghost_node_a",
                    imposed_value=1.0,
                ),
                ImposedMassFlowResidualDeclaration(
                    residual_name="r_ghost2",
                    mass_flow_unknown="mdot:ghost_component",
                    imposed_value=1.0,
                ),
            ]
        )
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=bad_set,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is False
        reasons = " ".join(result.compatibility.reasons)
        assert "P:n_ghost_node_a" in reasons or "ghost" in reasons

    def test_partial_missing_unknowns_is_incompatible(self) -> None:
        partial_set = build_configurable_algebraic_residual_set(
            [
                ImposedPressureResidualDeclaration(
                    residual_name="r_ok",
                    pressure_unknown="P:n_pump_out",  # exists in scenario
                    imposed_value=200_000.0,
                ),
                ImposedPressureResidualDeclaration(
                    residual_name="r_bad",
                    pressure_unknown="P:n_phantom",  # does not exist
                    imposed_value=1.0,
                ),
            ]
        )
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=partial_set,
        )
        result = select_configurable_residual_strategy(req)
        assert result.compatibility.is_compatible is False


# ---------------------------------------------------------------------------
# V4: Evaluation requires evaluate=True
# ---------------------------------------------------------------------------


class TestV4EvaluationRequiresEvalTrue:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_evaluate_false_does_not_evaluate(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=False,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is False
        assert result.evaluation_result is None

    def test_evaluate_true_does_evaluate(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is True


# ---------------------------------------------------------------------------
# V5: Evaluation requires algebraic_unknown_values
# ---------------------------------------------------------------------------


class TestV5EvaluationRequiresUnknownValues:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_missing_unknown_values_defers(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is False
        assert result.evaluation_deferred is True
        assert "algebraic_unknown_values" in result.evaluation_deferred_reason

    def test_provided_unknown_values_evaluates(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.evaluation_performed is True


# ---------------------------------------------------------------------------
# V6: result.no_solve is always True
# ---------------------------------------------------------------------------


class TestV6NoSolveAlwaysTrue:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_no_solve_true_without_evaluation(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
        )
        result = select_configurable_residual_strategy(req)
        assert result.no_solve is True

    def test_no_solve_true_with_evaluation(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        assert result.no_solve is True
        assert result.evaluation_result.no_solve is True

    def test_no_solve_true_incompatible(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
        )
        result = select_configurable_residual_strategy(req)
        assert result.no_solve is True


# ---------------------------------------------------------------------------
# V7: Report is JSON-serializable
# ---------------------------------------------------------------------------


class TestV7ReportJSONSerializable:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_report_serializable_without_eval(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        serialized = json.dumps(report)
        assert isinstance(serialized, str)

    def test_report_serializable_with_eval(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        serialized = json.dumps(report)
        loaded = json.loads(serialized)
        assert loaded["no_solve"] is True
        assert loaded["selected_mode"] == "configurable_algebraic"

    def test_report_serializable_incompatible(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        serialized = json.dumps(report)
        assert isinstance(serialized, str)


# ---------------------------------------------------------------------------
# V8: Report includes required unknown names and no-inference flags
# ---------------------------------------------------------------------------


class TestV8ReportNoInferenceFlags:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_report_no_solve_true(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
            algebraic_unknown_values=_ZERO_UV,
            evaluate=True,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        assert report["no_solve"] is True

    def test_report_no_role_physics(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        assert report["roles_selected_physics"] is False
        assert report["closures_inferred_from_roles"] is False
        assert report["residuals_inferred_from_roles"] is False
        assert report["residuals_inferred_from_topology"] is False

    def test_report_limitations_include_no_inference(self) -> None:
        req = ConfigurableResidualSelectionRequest(
            build_result=self.build_result,
            mode=ConfigurableResidualMode.CONFIGURABLE_ALGEBRAIC,
            algebraic_residual_set=self.residual_set,
        )
        result = select_configurable_residual_strategy(req)
        report = build_configurable_residual_selection_report(result)
        limitations = " ".join(report["limitations"])
        assert "residual" in limitations.lower()
        assert "role" in limitations.lower()


# ---------------------------------------------------------------------------
# R1/R2: Regression — production contracts
# ---------------------------------------------------------------------------


class TestRegressionProductionContracts:
    def test_all_known_classes_have_no_contribute_method(self) -> None:
        results = inspect_known_production_component_contracts()
        assert len(results) == 6
        for r in results:
            assert (
                r.status == ProductionComponentContractStatus.NO_CONTRIBUTE_METHOD
            ), f"{r.class_name} unexpectedly has contribute: {r.status!r}"

    def test_exactly_six_contracts_inspected(self) -> None:
        results = inspect_known_production_component_contracts()
        assert len(results) == 6


# ---------------------------------------------------------------------------
# B1-B4: Boundary — module attribute / import checks
# ---------------------------------------------------------------------------


class TestBoundaryModuleAttributes:
    def setup_method(self) -> None:
        import mpl_sim.network.configurable_residual_selection as _mod

        self.mod = _mod

    def test_no_coolprop_import(self) -> None:
        # Must not contain an executable import of CoolProp or PropertyBackend.
        # Documentation strings may mention these as constraints ("MUST NOT import...").
        # We check for import statements, not docstring mentions.
        source = inspect.getsource(self.mod)
        import_lines = [
            ln.strip()
            for ln in source.splitlines()
            if ln.strip().startswith("import ") or ln.strip().startswith("from ")
        ]
        import_text = "\n".join(import_lines)
        assert "CoolProp" not in import_text
        assert "PropertyBackend" not in import_text

    def test_no_contribute_attribute(self) -> None:
        assert not hasattr(self.mod, "contribute")
        source = inspect.getsource(self.mod)
        assert "def contribute" not in source

    def test_no_system_state_or_fluid_state_imports(self) -> None:
        # SystemState and FluidState must not be imported or instantiated.
        # They may appear in documentation strings as constraint names.
        source = inspect.getsource(self.mod)
        import_lines = [
            ln.strip()
            for ln in source.splitlines()
            if ln.strip().startswith("import ") or ln.strip().startswith("from ")
        ]
        import_text = "\n".join(import_lines)
        assert "SystemState" not in import_text
        assert "FluidState" not in import_text

    def test_no_solver_functions_defined(self) -> None:
        # Must not define solver entry-point functions.
        # The module docstring may mention "NetworkGraph.solve()" as a constraint.
        source = inspect.getsource(self.mod)
        assert "def solve_network" not in source
        # Verify no callable attribute named solve (or solve_network) is exported
        assert not hasattr(self.mod, "solve_network")
        assert not hasattr(self.mod, "NetworkGraph")

    def test_no_role_inference_for_residuals(self) -> None:
        source = inspect.getsource(self.mod)
        # Must not contain logic that auto-generates residuals from role values.
        assert "infer_residuals_from_role" not in source
        assert "generate_residuals_from_role" not in source

    def test_configurable_algebraic_residuals_module_no_bad_imports(self) -> None:
        import mpl_sim.network.configurable_algebraic_residuals as alg_mod

        source = inspect.getsource(alg_mod)
        import_lines = [
            ln.strip()
            for ln in source.splitlines()
            if ln.strip().startswith("import ") or ln.strip().startswith("from ")
        ]
        import_text = "\n".join(import_lines)
        assert "CoolProp" not in import_text
        assert "PropertyBackend" not in import_text
        assert "SystemState" not in import_text
        assert "FluidState" not in import_text


# ---------------------------------------------------------------------------
# Integration: validate_algebraic_residuals_against_scenario directly
# ---------------------------------------------------------------------------


class TestValidateAlgebraicResidualAgainstScenario:
    def setup_method(self) -> None:
        self.build_result = _build_scenario()
        self.residual_set = _make_residual_set()

    def test_compatible_set_reports_compatible(self) -> None:
        report = validate_algebraic_residuals_against_scenario(self.residual_set, self.build_result)
        assert report["is_compatible"] is True
        assert report["missing_unknowns"] == []
        assert report["no_residuals_inferred_from_roles"] is True
        assert report["no_residuals_inferred_from_topology"] is True

    def test_incompatible_set_reports_missing(self) -> None:
        bad_set = build_configurable_algebraic_residual_set(
            [
                ImposedPressureResidualDeclaration(
                    residual_name="r_ghost",
                    pressure_unknown="P:n_nonexistent",
                    imposed_value=1.0,
                ),
            ]
        )
        report = validate_algebraic_residuals_against_scenario(bad_set, self.build_result)
        assert report["is_compatible"] is False
        assert "P:n_nonexistent" in report["missing_unknowns"]

    def test_report_is_json_serializable(self) -> None:
        report = validate_algebraic_residuals_against_scenario(self.residual_set, self.build_result)
        serialized = json.dumps(report)
        assert isinstance(serialized, str)
